algoritmo "Estrutura SE"
// Função : Exibir mensagens na tela
// Autor :  Tiago Pantoja
// Data : 7/16/2021
// Seção de Declarações 
var
numero: inteiro
inicio
escreval ("Digitar um número entre 0 e 100")
leia (numero)
se (numero <= 10) entao
escreval ("Você é muito feliz")
fimse
se (numero > 11) e (numero < 19) entao
escreval ("Você é muito indeciso")
fimse
se (numero >= 20) entao
escreval ("Você está infeliz")
fimse
fimalgoritmo
